spring.application.name=songBot

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.chat-id=${TELEGRAM_BOT_CHAT_ID}
telegram.bot.message-thread-id=${TELEGRAM_BOT_MESSAGE_THREAD_ID}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:songbot_db;DB_CLOSE_DELAY=-1}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
